use std::env;
use std::fs;
use std::path::PathBuf;

/// Generate the correct `memory.x` for the selected board's MCU and make it
/// available to the linker. Flash/RAM sizes differ per chip:
///
/// | Board feature  | MCU         | Flash | RAM   |
/// |----------------|-------------|-------|-------|
/// | stm32f7        | STM32F767xG | 1 MiB | 512 K |
/// | stm32f4*       | STM32F407xG | 1 MiB | 192 K |
fn main() {
    // STM32F767 (Proteus) has 512 KiB of contiguous SRAM; the STM32F407 family
    // used by the other four boards has 192 KiB.
    let is_f7 = env::var_os("CARGO_FEATURE_STM32F7").is_some();
    let (flash_len, ram_len) = if is_f7 {
        ("1M", "512K")
    } else {
        ("1M", "192K")
    };

    let memory_x = format!(
        "/* Auto-generated by build.rs for the selected board MCU */\n\
         MEMORY\n\
         {{\n\
         \x20 FLASH : ORIGIN = 0x08000000, LENGTH = {flash_len}\n\
         \x20 RAM   : ORIGIN = 0x20000000, LENGTH = {ram_len}\n\
         }}\n"
    );

    let out = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(out.join("memory.x"), memory_x).expect("write memory.x");

    // Put OUT_DIR (containing the generated memory.x) on the linker search path.
    println!("cargo:rustc-link-search={}", out.display());
    println!("cargo:rerun-if-changed=build.rs");
}
